version: 2
jobs:
  build:
    docker:
      - image: node:8.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install -g karma-cli istanbul eslint
      - run: npm test
      - run: cat ./coverage/Chrome*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
